SELECT

    met_data.`id` AS `id`,
    cast(met_data.`fecha_hora` as date) AS `fecha`,
    cast(met_data.`fecha_hora` as time) AS `hora`,
    `stations`.`label` AS `station`,
    met_data.`intervalo` AS `intervalo`,
    met_data.`temperatura_interna` AS `temperatura_interna`,
    met_data.`temperatura_externa` AS `temperatura_externa`,
    met_data.`humedad_interna` AS `humedad_interna`,
    met_data.`humedad_externa` AS `humedad_externa`,
    met_data.`presion_relativa` AS `presion_relativa`,
    met_data.`presion_absoluta` AS `presion_absoluta`,
    met_data.`velocidad_viento` AS `velocidad_viento`,
    met_data.`sensacion_termica` AS `sensacion_termica`,
    met_data.`rafaga` AS `rafaga`,
    met_data.`direccion_del_viento` AS `direccion_del_viento`,
    met_data.`punto_rocio` AS `punto_rocio`,
    met_data.`lluvia_hora` AS `lluvia_hora`,
    met_data.`lluvia_24_horas` AS `lluvia_24_horas`,
    met_data.`lluvia_semana` AS `lluvia_semana`,
    met_data.`lluvia_mes` AS `lluvia_mes`,
    met_data.`lluvia_total` AS `lluvia_total`,
    met_data.`hi_temp` AS `hi_temp`,
    met_data.`low_temp` AS `low_temp`,
    met_data.`wind_cod` AS `wind_cod`,
    met_data.`wind_run` AS `wind_run`,
    met_data.`hi_speed` AS `hi_speed`,
    met_data.`hi_dir` AS `hi_dir`,
    met_data.`wind_cod_dom` AS `wind_cod_dom`,
    met_data.`wind_chill` AS `wind_chill`,
    met_data.`index_heat` AS `index_heat`,
    met_data.`index_thw` AS `index_thw`,
    met_data.`index_thsw` AS `index_thsw`,
    met_data.`rain` AS `rain`,
    met_data.`solar_rad` AS `solar_rad`,
    met_data.`solar_energy` AS `solar_energy`,
    met_data.`radsolar_max` AS `radsolar_max`,
    met_data.`uv_index` AS `uv_index`,
    met_data.`uv_dose` AS `uv_dose`,
    met_data.`uv_max` AS `uv_max`,
    met_data.`heat_days_d` AS `heat_days_d`,
    met_data.`cool_days_d` AS `cool_days_d`,
    met_data.`in_dew` AS `in_dew`,
    met_data.`in_heat` AS `in_heat`,
    met_data.`in_emc` AS `in_emc`,
    met_data.`in_air_density` AS `in_air_density`,
    met_data.`evapotran` AS `evapotran`,
    met_data.`soil_1_moist` AS `soil_1_moist`,
    met_data.`soil_2_moist` AS `soil_2_moist`,
    met_data.`leaf_wet1` AS `leaf_wet1`,
    met_data.`leaf_wet2` AS `leaf_wet2`,
    met_data.`leaf_wet3` AS `leaf_wet3`,
    met_data.`leaf_wet4` AS `leaf_wet4`,
    met_data.`wind_samp` AS `wind_samp`,
    met_data.`wind_tx` AS `wind_tx`,
    met_data.`iss_recept` AS `iss_recept`,
    met_data.`meteobridge` AS `meteobridge`

FROM (met_data LEFT JOIN `stations` ON((`stations`.`id` = met_data.`station_id`)))
